service: products-serverless-s3-queue
frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: us-east-2

resources:
  Resources:
    UploadBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "products-serverless-course-bucket-${self:provider.stage}"
